					<article id="discografia">
						<h1><img src="img/layout/titulo-discografia.svg" alt="Discografía"></h1>
						<a class="cerrar"><img src="img/layout/cerrar.svg" alt="Cerrar"></a>
						<h2>Descargá la discografía completa de Infanto-Juvenil</h2>
						<ul>
							<li>
								<a href="https://drive.google.com/open?id=0B-MCBxTP83NfVXpJMGx3cEZqRzg" target="_parent">
									<img src="img/contenido/discografia-demo-1.jpg" alt="Demo 1">
									<h1>Demo 1</h1>
									<p>Julio 2003</p>
								</a>
							</li>
							<li>
								<a href="https://drive.google.com/open?id=0B-MCBxTP83NfV0czM3JYSnFjcWs" target="_parent">
									<img src="img/contenido/discografia-muestra-virginia.jpg" alt="Muestra para Virginia">
									<h1>Muestra <br>para Virginia</h1>
									<p>Julio 2003</p>
								</a>
							</li>
							<li>
								<a href="https://drive.google.com/open?id=0B-MCBxTP83NfUS1MN3lJN3c0cHc" target="_parent">
									<img src="img/contenido/discografia-demo-2.jpg" alt="Demo 2">
									<h1>Demo 2</h1>
									<p>Abril 2004</p>
								</a>
							</li>
							<li>
								<a href="https://infantojuvenil.bandcamp.com/album/infanto-juvenil" target="_parent">
									<img src="img/contenido/discografia-demo-3.jpg" alt="Demo 3">
									<h1>Demo 3 (garageband)</h1>
									<p>Setiembre 2014</p>
								</a>
							</li>
						</ul>
					</article>