					<article id="historia">
						<h1><img src="img/layout/titulo-historia.svg" alt="Historia"></h1>
						<a class="cerrar"><img src="img/layout/cerrar.svg" alt="Cerrar"></a>
						
						<div>
							<p>En una ciudad olvidada, en el invierno eterno, surge Infanto-Juvenil, primer y único grupo punk de Piriápolis.</p>
							<p>El grupo surge en el año 2003, en un contexto de bandas jóvenes <br>sin temas propios, sin nada para decir.</p>
							<p>Infanto-Juvenil se ubica en el polo opuesto, fue un ataque adolescente <br>a los valores patrióticos, al orgullo nacional, la provocación constante <br>y un gusto especial por hacerse odiar.</p>
						</div>
						
					</article>